import styled from 'styled-components';
import theme from '../../styles/Global.styles';

export const MenuDiv = styled.div`
    // padding: 0 31px 0 0;
    // display: flex;
    // align-items: flex-start;
    position: absolute;
    width: 720px;
    height: 72px;
    left: 893px;
    top: 119px;
`;
export const MenuGroup = styled.div`
    background-color: ${theme.colors.white};
    // padding: 0 31px 0 0;
    // display: flex;
    // align-items: flex-start;
    position: absolute;
    left: 0%;
    right: 0%;
    top: 0%;
    bottom: 0%;
`;
export const NavHighlight = styled.div`
    background-color: ${theme.colors.darkKhaki};
    // margin-right: 42px;
    // padding: 17px 30.56px 22px 36.24px;
    // display: flex;
    // align-items: flex-start;
    position: absolute;
    left: 0%;
    right: 78.75%;
    top: 0%;
    bottom: 0%;
`;
export const NavHome = styled.p`
    color: ${theme.colors.white};
    // width: 100%;
    // align-self: stretch;
    // display: flex;
    position: absolute;
    left: 5.03%;
    right: 82.99%;
    top: 23.61%;
    bottom: 30.56%;
    font-family: ${theme.fonts.roboto30Regular.family};
    font-size: ${theme.fonts.roboto30Regular.size};
    font-weight: ${theme.fonts.roboto30Regular.weight};
    line-height: ${theme.fonts.roboto30Regular.lineHeight};
`;
export const NavAbout = styled.p`
    color: ${theme.colors.black};
    // height: 45.83%;
    // width: 12.37%;
    // display: flex;
    // margin-top: 17px;
    // margin-right: 72.78px;
    position: absolute;
    left: 27.08%;
    right: 61.08%;
    top: 23.61%;
    bottom: 30.56%;
    font-family: ${theme.fonts.roboto30Regular.family};
    font-size: ${theme.fonts.roboto30Regular.size};
    font-weight: ${theme.fonts.roboto30Regular.weight};
    line-height: ${theme.fonts.roboto30Regular.lineHeight};
`;
export const NavServices = styled.p`
    color: ${theme.colors.black};
    // height: 45.83%;
    // width: 16.49%;
    // display: flex;
    // margin-top: 17px;
    // margin-right: 72.37px;
    position: absolute;
    left: 49.03%;
    right: 35.19%;
    top: 23.61%;
    bottom: 30.56%;
    font-family: ${theme.fonts.roboto30Regular.family};
    font-size: ${theme.fonts.roboto30Regular.size};
    font-weight: ${theme.fonts.roboto30Regular.weight};
    line-height: ${theme.fonts.roboto30Regular.lineHeight};
`;
export const NavContact = styled.p`
    color: ${theme.colors.black};
    // height: 45.83%;
    // width: 21.77%;
    // display: flex;
    // margin-top: 17px;
    position: absolute;
    left: 74.86%;
    right: 4.31%;
    top: 23.61%;
    bottom: 30.56%;
    font-family: ${theme.fonts.roboto30Regular.family};
    font-size: ${theme.fonts.roboto30Regular.size};
    font-weight: ${theme.fonts.roboto30Regular.weight};
    line-height: ${theme.fonts.roboto30Regular.lineHeight};
`;
